config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, 
            :path => '', 
            :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile' },
            :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                              :registrations => 'registrations'
                              }

  resources :users, only: [:show]
  resources :courses
  resources :photos

  resources :courses do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :courses do
    resources :reviews, only: [:create, :destroy]
  end

  get '/your_enrolled_courses' => 'reservations#your_enrolled_courses'
  get '/your_students' => 'reservations#your_students'

  get '/search' => 'pages#search'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :authenticate_user!

	def create
		course = Course.find(params[:course_id])
		if(current_user==course.user)
			redirect_to course, notice: "You have already enrolled in this course!"
		else
			@reservation = current_user.reservations.create(reservation_params)

			redirect_to @reservation.course, notice: "You have enrolled successfully."
		end
	end

	def your_enrolled_courses
		@enrolled_courses = current_user.reservations
	end

	def your_students
		@courses = current_user.courses
	end

	private 
		def reservation_params
			params.require(:reservation).permit(:start_date, :price, :course_id)
		end

end

app/views/reservations/_form.html.erb
<%= form_for([@course, @course.reservations.new]) do |f| %>

	<span>Start Date:</span>
	<%= f.text_field :start_date, readonly:'true', placeholder: 'Select Date', class: 'form-control' %>
	<%= f.hidden_field :course_id, value: @course.id %>
	<%= f.hidden_field :price, value: @course.price %>



	<div id="preview" style="display:none">
		<% if(@course.price) %>
		<br>
		<table class="reservation-table">
			<tbody>
				<tr>
					<td>Total Cost:</td>
					<td><span id="reservation_cost">$<%= @course.price %></span></td>
				</tr>
			</tbody>
		</table>
		<% end %>

	</div>
	<br>
	<%= f.submit "Enroll Now", id: "btn_book", class: "btn btn-primary wide", disabled: 'true' %>
	
<% end %>

<script>
	$(function() {
		var dateToday = new Date();
		$('#reservation_start_date').datepicker({
			dateFormat: 'dd-mm-yy',
			minDate: dateToday,
			onSelect: function(selected) {
					$('#preview').show();
					$('#btn_book').attr('disabled', false);
			}
		});
	});
</script>

app/views/reservations/your_enrolled_courses.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			
			<li class="sidebar-item"><%= link_to "Enrolled Courses", your_enrolled_courses_path, class: "sidebar-link active" %></li>
			<li class="sidebar-item"><%= link_to "Your Submitted Courses", courses_path, class: "sidebar-link " %></li>
			<li class="sidebar-item"><%= link_to "Your Students", your_students_path, class: "sidebar-link" %></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Enrolled Courses
			</div>
			<div class="panel-body">
				<% @enrolled_courses.each do |enrolled_course| %>
					<div class="row">
						<div class="col-md-2">
							<%= link_to course_path(enrolled_course.course) do %>
							<%= image_tag enrolled_course.course.photos[0].image.url(:thumb) if enrolled_course.course.photos.length > 0 %>
							<% end %>
						</div>
						<div class="col-md-6">
							<%= link_to course_path(enrolled_course.course) do %>
							<h4><%= enrolled_course.course.title %></h4>
							<% end %>
							<%= enrolled_course.course.about %><br>
							<span style="color:red">
								<% if(enrolled_course.course.price) %>
										$<%= enrolled_course.course.price %>
								<% elsif(enrolled_course.course.freeorpaid =="Free") %>
									Free
								<% end %>
							</span>

						</div>
						<div class="col-md-2">
							<h5>Start Date:</h5>
							<%= enrolled_course.start_date.strftime('%v') %>
						</div>
						
						<div class="col-md-2">
							<h5>Taught By:</h5>
							<%= link_to user_path(enrolled_course.course.user) do %>
							<%= image_tag avatar_url(enrolled_course.course.user), class: "img-circle avatar-medium"%><br>
							<h5><%= enrolled_course.course.user.fullname %></h5>
							<% end %>
							
						</div>
					</div>
					<hr>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/reservations/your_students.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			
			<li class="sidebar-item"><%= link_to "Enrolled Courses", your_enrolled_courses_path, class: "sidebar-link" %></li>
			<li class="sidebar-item"><%= link_to "Your Submitted Courses", courses_path, class: "sidebar-link " %></li>
			<li class="sidebar-item"><%= link_to "Your Students", your_students_path, class: "sidebar-link active" %></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Students
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-2">
						<h4>Student:</h4>
					</div>
					<div class="col-md-10">
						<h4>Course:</h4>
					</div>
				</div>
				<hr>

				<% @courses.each do |course| %>
					<% course.reservations.each do |reservation| %>
					<div class="row">
						<div class="col-md-2">
							
							<%= link_to user_path(reservation.user) do %>
							<%= image_tag avatar_url(reservation.user), class: "img-circle avatar-medium"%><br>
							<h5><%= reservation.user.fullname %></h5>
							<% end %>
							
						</div>
						<div class="col-md-2">
							<%= link_to course_path(reservation.course) do %>
							<%= image_tag reservation.course.photos[0].image.url(:thumb) if reservation.course.photos.length > 0 %>
							<% end %>
						</div>
						<div class="col-md-6">
							<%= link_to course_path(reservation.course) do %>
							<h4><%= reservation.course.title %></h4>
							<% end %>
							<%= reservation.course.about %><br>
							<span style="color:red">
								<% if(reservation.course.price) %>
										$<%= reservation.course.price %>
								<% elsif(reservation.course.freeorpaid =="Free") %>
									Free
								<% end %>
							</span>

						</div>
						<div class="col-md-2">
							<h5>Start Date:</h5>
							<%= reservation.start_date.strftime('%v') %>
						</div>
						
						
					</div>
					<hr>
				<% end %>

				<% end %>
				
			</div>
		</div>
	</div>
</div>